name = "my-proxy"                  # Your worker name (change if you want)
main = "worker.js"                  # Your main JavaScript file name 
compatibility_date = "2025-06-09" # Use today's date in YYYY-MM-DD format